language: java
env:
- PLAY_VERSION=2.2.2
before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- cp conf/application.smtp.conf.sample conf/application.smtp.conf
script: play-${PLAY_VERSION}/play test