language: java
env:
  global:
    - APP_VERSION=0.3-SNAPSHOT
    - ACTIVATOR_VERSION=1.3.2
    - PATH=/tmp/activator-${ACTIVATOR_VERSION}-minimal:$PATH
  matrix:
    - CONF=conf/unit-test.conf
    - CONF=conf/unit-test.postgresql.conf
addons:
  postgresql: "9.3"
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
before_script:
- npm install -g grunt-cli
- npm install -g bower
- cd ui
- npm install
- bower install
- grunt dev
- wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip -qO /tmp/activator.zip
- unzip -qd /tmp /tmp/activator.zip
- psql -c "CREATE USER oot WITH PASSWORD 'oot';" -U postgres
- psql -c "CREATE DATABASE oot OWNER oot;" -U postgres
- cd ..
script:
- activator -Dconfig.file=${CONF} test
- activator -Dconfig.file=${CONF} -Dselenium.driver=firefox cucumber
before_deploy:
- echo "{version: `git describe --tags`}" > target/scala-2.11/classes
- cd ui; grunt prod
- cd ..; activator dist
deploy:
  provider: releases
  api_key:
    secure: VIplPeNwvG7XEgvlRHgemwXeQjK10fXWZC6x+PjPOLchm7d2/FzQXjiQhiDfkN3AowDhKMmNHCtI2e4zVPpNTKPkoXIcLqZ081DJaTx4iKr+5EKuu+O0GDY8a165T6I3zbJdIGsekc6qb9J3YQrKbax8/eC4QxaFE2Ws/iRsuPU=
  file: target/universal/oot-webapp-${APP_VERSION}.zip
  skip_cleanup: true
  on:
    tags: true
    repo: agilecommunity/oot
notifications:
  slack: agilecom:dyFpi9UUyhS10BazKyNsSf13
sudo: false
