language: java
env:
- PLAY_VERSION=2.2.2
- APP_VERSION=1.0-SNAPSHOT
before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- npm install -g grunt-cli
- npm install -g bower
- cd oot/ui
- npm install
- bower install
- grunt dev
- cd ../
script: play-${PLAY_VERSION}/play dist
after_script:
- rm -rf play-${PLAY_VERSION}
- rm -f play-${PLAY_VERSION}.zip
deploy:
  provider: releases
  api_key:
    secure: JJ+mwgkitgDNmVJDz5wl6/hRNXODjhVf6hvDFQWj43/66Jya+6ayPO7ElkeF86lnhVPzpBRK1vrdb2gvWyAqvQgVI1H6EjYvBFsw7YmcgHnehLQFutJBVpCqZqtY+vkbQHPV9Jk9AxTUZ7ZusSrVFW1KvyFc6q3yG1tC6/H5pCI=
  file: /home/travis/build/nobiinu-and/oot/target/universal/oot-webapp-${APP_VERSION}.zip
  on:
    repo: nobiinu-and/oot
    branch: develop
