language: java
env:
- PLAY_VERSION=2.2.2
before_script:
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- npm install bower
- cd ui; npm install; bower install; grunt dev
script: play-${PLAY_VERSION}/play dist
