language: java
env:
  global:
    - APP_VERSION=0.2-SNAPSHOT
    - ACTIVATOR_VERSION=1.3.2
    - PATH=/tmp/activator-${ACTIVATOR_VERSION}-minimal:$PATH
  matrix:
    - CONF=conf/unit-test.conf
    - CONF=conf/unit-test.postgresql.conf
addons:
  postgresql: "9.3"
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
before_script:
- wget http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip -qO /tmp/activator.zip
- unzip -qd /tmp /tmp/activator.zip
- npm install -g grunt-cli
- npm install -g bower
- cd oot/ui
- npm install
- bower install
- grunt dev
- cd ../
- psql -c "CREATE USER oot WITH PASSWORD 'oot';" -U postgres
- psql -c "CREATE DATABASE oot OWNER oot;" -U postgres
script:
- activator -Dconfig.file=${CONF} test
- activator -Dconfig.file=${CONF} -Dselenium.driver=firefox cucumber
notifications:
  slack: agilecom:dyFpi9UUyhS10BazKyNsSf13
sudo: false
