language: java
env:
  global:
    - PLAY_VERSION=2.3.8
    - APP_VERSION=1.0-SNAPSHOT
  matrix:
    - CONF=conf/unit-test.conf
    - CONF=conf/unit-test.postgresql.conf
addons:
  postgresql: "9.3"
before_install:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
before_script:
- cd ..
- wget http://downloads.typesafe.com/play/${PLAY_VERSION}/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- npm install -g grunt-cli
- npm install -g bower
- cd oot/ui
- npm install
- bower install
- grunt dev
- cd ../
- psql -c "CREATE USER oot WITH PASSWORD 'oot';" -U postgres
- psql -c "CREATE DATABASE oot OWNER oot;" -U postgres
script:
- ../play-${PLAY_VERSION}/play -Dconfig.file=${CONF} test
- ../play-${PLAY_VERSION}/play -Dconfig.file=${CONF} -Dselenium.driver=firefox cucumber
notifications:
  slack: agilecom:dyFpi9UUyhS10BazKyNsSf13
sudo: false
